name: Node.js CI

on:
  schedule:
    # every day at 2am
#     - cron: "0 2 * * *"
  push:
#     branches: [master]
  pull_request:
#     branches: [master]

jobs:
  audit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn
          yarn dedupe --check
          yarn npm audit --environment production
